name: Deploy Express Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install yt-dlp
          sudo apt install -y nodejs npm
          npm install express cors

      - name: Start Express Server in Background
        run: nohup node server.js > server.log 2>&1 &
