name: Restart Server Every 5 Hours

on:
  schedule:
    - cron: "0 */5 * * *"  # প্রতি ৫ ঘণ্টা পর পর রান হবে
  workflow_dispatch:  # চাইলে ম্যানুয়ালি রান করা যাবে

jobs:
  restart-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install yt-dlp
          sudo apt install -y nodejs npm
          npm install express cors

      - name: Start Server
        run: nohup node server.js > server.log 2>&1 &
